on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: djangoregistryayan.azurecr.io
        username: ${{ secrets.acr_djangoregistryayan_username }}
        password: ${{ secrets.acr_djangoregistryayan_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t djangoregistryayan.azurecr.io/vivacluster:${{ github.sha }}
        docker push djangoregistryayan.azurecr.io/vivacluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vivacluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vivacluster9780 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vivacluster9780`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vivacluster9780
        container-registry-url: djangoregistryayan.azurecr.io
        container-registry-username: ${{ secrets.acr_djangoregistryayan_username }}
        container-registry-password: ${{ secrets.acr_djangoregistryayan_password }}
        secret-name: vivaclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vivacluster9780
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          djangoregistryayan.azurecr.io/vivacluster:${{ github.sha }}
        imagepullsecrets: |
          vivaclusterdockerauth