on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n djangoregistryayan -g djangoregistryayan936d-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n djangoregistryayan --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n djangoregistryayan --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n djangoregistryayan --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: djangoregistryayan.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Dockerfile-tools" -f  "Dockerfile" -t djangoregistryayan.azurecr.io/vivacluster:${{ github.sha }}
        docker push djangoregistryayan.azurecr.io/vivacluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_vivacluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vivaclustere3f3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vivaclustere3f3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vivaclustere3f3
        container-registry-url: djangoregistryayan.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: vivaclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vivaclustere3f3
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          djangoregistryayan.azurecr.io/vivacluster:${{ github.sha }}
        imagepullsecrets: |
          vivaclusterdockerauth